-- CRIANDO UM BANCO DE DADOS
CREATE DATABASE AGENDA;
-- SELECIONADO UM BANCO DE DADOS
USE AGENDA;
-- CRIANDO TABELA NO BANCO DE DADOS
CREATE TABLE TB_PESSOAS(
COD INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(30)NOT NULL UNIQUE,
ENDERECO VARCHAR(100),
TELEFONE VARCHAR(11) NOT NULL UNIQUE,
EMAIL VARCHAR(35)
);
-- MOSTRANDO AS TABELAS NO BANCO DE DADOS
SHOW TABLES;
-- DESCREVENDO A TABELA;
DESCRIBE TB_PESSOAS;
-- INSERINDO DASOS NA TABELA
INSERT INT TB_PESSOAS VALUES(
'ANDERSON',
'RUA ITAPIRANGA N412 D IPUTINGA RECIFE-PE',
'81986082675',
'anderson@gmail.com'
);
-- DELETANDO UMA TABELA
DROP TABLE TB_PESSOAS;










